"""Role-driven nftables drop-in renderer for the supervisor (#170 Wave C3).

Builds the body of ``/etc/nftables.d/spatium-role.nft`` from the
control plane's ``role_assignment`` block. The host's master
``/etc/nftables.conf`` includes everything under
``/etc/nftables.d/*.nft`` inside the inet filter table's ``input``
chain (same pattern the SNMP / NTP drop-ins already use, per
#153 + #154).

Always-open management rules (regardless of role):

* SSH (operator escape hatch).
* ICMP echo-request (monitoring).
* Loopback.
* Established / related (the master conf's first input rule
  already covers this — we don't restate it).

Per-role openings:

* ``dns-bind9`` / ``dns-powerdns``: UDP + TCP / 53.
* ``dhcp``: UDP / 67, 68.
* ``observer``: no ports — runs as a metrics shipper.
* ``custom``: no ports.

Operator override: ``firewall_extra`` is appended verbatim at the
end of the drop-in. The supervisor runs ``nft -c -f`` against the
generated file before live-swap; a syntax error rejects the apply
without leaving the firewall in a half-rendered state.

Pure functions only — the actual file write + ``nft -f`` invocation
lives in the supervisor's heartbeat loop alongside the role-env
write, sharing the same atomic-rename + validation shape.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Any


@dataclass(frozen=True)
class FirewallProfile:
    """Result of compiling a role_assignment block into an nftables
    drop-in body.

    ``name`` is the operator-friendly profile label rendered in the
    fleet UI ("dns-only" / "dns-and-dhcp" / "idle"); the supervisor
    logs it on each apply so journalctl shows the active profile
    without having to inspect the file itself.

    ``expected_tcp_ports`` + ``expected_udp_ports`` carry the role-
    derived service ports the supervisor's periodic live-ruleset
    check inspects via ``nft list chain inet filter input`` (#170
    Wave D follow-up — drift detection on the firewall, mirroring
    the same shape as the container-watchdog idea in the open #170
    follow-up). Empty for idle / observer / custom roles.
    """

    name: str
    body: str
    expected_tcp_ports: frozenset[int] = frozenset()
    expected_udp_ports: frozenset[int] = frozenset()


# Per-role port set. Empty list = no service ports opened (the
# role still runs, just doesn't accept inbound traffic on a known
# port — observer is the canonical example).
_ROLE_PORTS_TCP: dict[str, list[int]] = {
    "dns-bind9": [53],
    "dns-powerdns": [53],
}
_ROLE_PORTS_UDP: dict[str, list[int]] = {
    "dns-bind9": [53],
    "dns-powerdns": [53],
    "dhcp": [67, 68],
}


def _profile_name(roles: list[str]) -> str:
    has_dns = any(r in roles for r in ("dns-bind9", "dns-powerdns"))
    has_dhcp = "dhcp" in roles
    if has_dns and has_dhcp:
        return "dns-and-dhcp"
    if has_dns:
        return "dns-only"
    if has_dhcp:
        return "dhcp-only"
    return "idle"


def render_drop_in(role_assignment: dict[str, Any] | None) -> FirewallProfile:
    """Translate a role_assignment block into an nftables drop-in body.

    Always emits the management rules + per-role rules + the
    operator's ``firewall_extra`` (if any). Idle (no roles)
    appliances get a body with management rules only — the appliance
    stays SSH-reachable + pingable but doesn't accept any service
    traffic.

    Header carries a "generated by spatium-supervisor" warning + the
    profile name so operators inspecting the file know what created
    it and what role set is currently active.
    """
    role_assignment = role_assignment or {}
    roles = [r for r in (role_assignment.get("roles") or []) if isinstance(r, str)]
    firewall_extra = role_assignment.get("firewall_extra") or ""
    # Issue #183 Phase 6 — operator-controlled CIDR allowlist for
    # direct kubeapi access on tcp/6443. Empty / missing = proxy-
    # only (kubeapi stays on 127.0.0.1; only the supervisor's
    # outbound proxy channel can drive it).
    kubeapi_cidrs = [
        c
        for c in (role_assignment.get("kubeapi_expose_cidrs") or [])
        if isinstance(c, str) and c.strip()
    ]

    profile = _profile_name(roles)
    lines: list[str] = []
    lines.append(
        "# Auto-generated by spatium-supervisor — do not hand-edit. "
        "See /etc/spatiumddi/firewall-extra on the host (or the fleet UI)"
    )
    lines.append(
        "# for the operator-override surface that lands at the end of this file."
    )
    lines.append(f"# profile: {profile}")
    lines.append(f"# roles: {','.join(roles) if roles else '(idle)'}")
    lines.append("")
    lines.append("# ── Management (always open) ────────────────────────────────")
    lines.append('tcp dport 22 accept comment "ssh"')
    lines.append('icmp type echo-request accept comment "icmpv4 ping"')
    lines.append('icmpv6 type echo-request accept comment "icmpv6 ping"')
    lines.append('iif lo accept comment "loopback"')

    # Per-role openings. UDP first then TCP so re-reading the file
    # follows the "lower-layer protocol then higher" mental model.
    tcp_ports: set[int] = set()
    udp_ports: set[int] = set()
    for role in roles:
        tcp_ports.update(_ROLE_PORTS_TCP.get(role, []))
        udp_ports.update(_ROLE_PORTS_UDP.get(role, []))

    if udp_ports or tcp_ports:
        lines.append("")
        lines.append("# ── Per-role service ports ─────────────────────────────")
    for port in sorted(udp_ports):
        lines.append(f'udp dport {port} accept comment "role:{profile}"')
    for port in sorted(tcp_ports):
        lines.append(f'tcp dport {port} accept comment "role:{profile}"')

    # Issue #183 Phase 6 — kubeapi direct-access allowlist. One
    # ``ip saddr { ... } tcp dport 6443 accept`` rule when non-
    # empty; complements the Phase 4 outbound proxy (which works
    # regardless of these CIDRs). The supervisor's drift checker
    # tracks ``tcp/6443`` in ``expected_tcp_ports`` only when the
    # allowlist is non-empty — proxy-only mode keeps it OUT of the
    # expected set so the drift watcher doesn't false-positive a
    # missing rule.
    if kubeapi_cidrs:
        lines.append("")
        lines.append("# ── kubeapi (operator-allowed CIDRs, #183 Phase 6) ──────")
        # nft accepts a comma-separated saddr set inline; quote-strip
        # each entry on the way in (operator-supplied) so a stray
        # whitespace doesn't break the parse.
        cidrs_inline = ", ".join(c.strip() for c in kubeapi_cidrs)
        lines.append(
            f"ip saddr {{ {cidrs_inline} }} tcp dport 6443 accept "
            f'comment "kubeapi-direct"'
        )
        tcp_ports.add(6443)

    if firewall_extra.strip():
        lines.append("")
        lines.append("# ── Operator override (firewall_extra) ─────────────────")
        # Strip a trailing newline so we don't get a blank line at EOF;
        # we'll add one in the join below.
        lines.append(firewall_extra.rstrip("\n"))

    body = "\n".join(lines) + "\n"
    return FirewallProfile(
        name=profile,
        body=body,
        expected_tcp_ports=frozenset(tcp_ports),
        expected_udp_ports=frozenset(udp_ports),
    )


__all__ = ["FirewallProfile", "render_drop_in"]
