"""Role orchestration on the supervisor (#170 Wave C2).

Translates the control plane's ``role_assignment`` heartbeat block
into a docker-compose env file the supervisor uses to bring up /
down the service containers:

* ``COMPOSE_PROFILES`` carries the subset of
  ``dns-bind9`` / ``dns-powerdns`` / ``dhcp`` the supervisor needs
  to start.
* ``DNS_AGENT_KEY`` / ``DHCP_AGENT_KEY`` / ``AGENT_GROUP`` /
  ``CONTROL_PLANE_URL`` carry the service-container env so the
  dns-bind9 / dhcp-kea agent sidecar can register against the
  control plane's per-service ``/dns/agents/register`` /
  ``/dhcp/agents/register`` endpoints without operator input.
* ``DHCP_NETWORK_MODE`` toggles ``network_mode: host`` (default)
  vs ``ports: ["67:67/udp"]`` (bridged, for relay deployments).
  The compose template selects between two service definitions
  based on this env var.

C2 ships the **env-rendering half** — the supervisor writes the
target file but doesn't yet invoke ``docker compose up -d``. The
actual lifecycle (load baked image, atomic role-switch with
revert-on-failure) lands in C3 alongside the nftables renderer
since both need the same subprocess machinery.

A clean ``compute_target_env()`` separates the pure computation
from any I/O so it's unit-testable + the C3 commit just plugs the
subprocess piece in next to it.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Any


# Roles the supervisor knows how to start a service container for.
# ``observer`` + ``custom`` are reserved (no compose profile yet);
# the supervisor recognises them on heartbeat but does nothing.
_SERVICE_ROLES = {"dns-bind9", "dns-powerdns", "dhcp"}


@dataclass(frozen=True)
class TargetEnv:
    """Result of computing the supervisor's target compose env.

    Lines are env-file format (``KEY=VALUE`` one per line, quoted
    when the value contains whitespace). ``profiles`` is included
    separately for callers that want to drive compose via CLI flags
    rather than env-var substitution.
    """

    env_lines: list[str]
    profiles: list[str]


def compute_target_env(role_assignment: dict[str, Any] | None) -> TargetEnv:
    """Translate the heartbeat response's ``role_assignment`` block
    into a list of env-file lines + the compose profile set.

    Empty / missing role list → empty profiles → supervisor brings
    down every service container (idle state). Same shape applies
    when the operator clears the role assignment via the API:
    the heartbeat returns ``roles=[]`` and the supervisor drops to
    idle on the next tick.

    Always emits ``COMPOSE_PROFILES`` so the env file can replace
    the operator-supplied one — never silently inherits.
    """
    role_assignment = role_assignment or {}
    roles = list(role_assignment.get("roles") or [])
    profiles: list[str] = []

    for role in roles:
        if role in _SERVICE_ROLES:
            profiles.append(role)

    env_lines: list[str] = []
    env_lines.append(f"COMPOSE_PROFILES={','.join(profiles)}")

    # DNS group config — only populated when a DNS role is assigned.
    dns_group_name = role_assignment.get("dns_group_name")
    dns_engine = role_assignment.get("dns_engine")
    if any(r in roles for r in ("dns-bind9", "dns-powerdns")):
        if dns_group_name:
            env_lines.append(f"AGENT_GROUP={dns_group_name}")
        if dns_engine:
            env_lines.append(f"DNS_ENGINE={dns_engine}")

    # DHCP group config.
    dhcp_group_name = role_assignment.get("dhcp_group_name")
    dhcp_network_mode = role_assignment.get("dhcp_network_mode") or "host"
    if "dhcp" in roles:
        if dhcp_group_name:
            # AGENT_GROUP is overloaded — DNS + DHCP can't be in the
            # same group anyway (different drivers), so when both
            # roles are assigned we still write one AGENT_GROUP and
            # let the compose templates per-role override via
            # role-specific env vars (Wave C3 reshape; for now we
            # emit a second AGENT_GROUP line — the later wins under
            # docker-compose's env-file parser).
            env_lines.append(f"DHCP_AGENT_GROUP={dhcp_group_name}")
        env_lines.append(f"DHCP_NETWORK_MODE={dhcp_network_mode}")

    return TargetEnv(env_lines=env_lines, profiles=profiles)


def render_env_file(target: TargetEnv, header: str | None = None) -> str:
    """Format a TargetEnv as a docker-compose env-file. Includes a
    ``# generated by spatium-supervisor`` header by default so the
    operator inspecting the file knows it shouldn't be hand-edited
    (every heartbeat overwrites)."""
    lines: list[str] = []
    if header:
        lines.append(header.rstrip("\n"))
    else:
        lines.append("# Auto-generated by spatium-supervisor — do not hand-edit.")
        lines.append("# Overwritten on every supervisor heartbeat that returns a")
        lines.append("# role_assignment block from the control plane.")
    lines.extend(target.env_lines)
    return "\n".join(lines) + "\n"


__all__ = ["TargetEnv", "compute_target_env", "render_env_file"]
