"""Role orchestration on the supervisor (#170 Wave C2).

Translates the control plane's ``role_assignment`` heartbeat block
into a docker-compose env file the supervisor uses to bring up /
down the service containers:

* ``COMPOSE_PROFILES`` carries the subset of
  ``dns-bind9`` / ``dns-powerdns`` / ``dhcp`` the supervisor needs
  to start.
* ``DNS_AGENT_KEY`` / ``DHCP_AGENT_KEY`` / ``AGENT_GROUP`` /
  ``CONTROL_PLANE_URL`` carry the service-container env so the
  dns-bind9 / dhcp-kea agent sidecar can register against the
  control plane's per-service ``/dns/agents/register`` /
  ``/dhcp/agents/register`` endpoints without operator input.
* ``DHCP_NETWORK_MODE`` toggles ``network_mode: host`` (default)
  vs ``ports: ["67:67/udp"]`` (bridged, for relay deployments).
  The compose template selects between two service definitions
  based on this env var.

C2 ships the **env-rendering half** — the supervisor writes the
target file but doesn't yet invoke ``docker compose up -d``. The
actual lifecycle (load baked image, atomic role-switch with
revert-on-failure) lands in C3 alongside the nftables renderer
since both need the same subprocess machinery.

A clean ``compute_target_env()`` separates the pure computation
from any I/O so it's unit-testable + the C3 commit just plugs the
subprocess piece in next to it.
"""

from __future__ import annotations

import re
import shutil
import subprocess
from dataclasses import dataclass
from typing import Any


# Roles the supervisor knows how to start a service container for.
# ``observer`` + ``custom`` are reserved (no compose profile yet);
# the supervisor recognises them on heartbeat but does nothing.
_SERVICE_ROLES = {"dns-bind9", "dns-powerdns", "dhcp"}


@dataclass(frozen=True)
class TargetEnv:
    """Result of computing the supervisor's target compose env.

    Lines are env-file format (``KEY=VALUE`` one per line, quoted
    when the value contains whitespace). ``profiles`` is included
    separately for callers that want to drive compose via CLI flags
    rather than env-var substitution.
    """

    env_lines: list[str]
    profiles: list[str]


def compute_target_env(role_assignment: dict[str, Any] | None) -> TargetEnv:
    """Translate the heartbeat response's ``role_assignment`` block
    into a list of env-file lines + the compose profile set.

    Empty / missing role list → empty profiles → supervisor brings
    down every service container (idle state). Same shape applies
    when the operator clears the role assignment via the API:
    the heartbeat returns ``roles=[]`` and the supervisor drops to
    idle on the next tick.

    Always emits ``COMPOSE_PROFILES`` so the env file can replace
    the operator-supplied one — never silently inherits.
    """
    role_assignment = role_assignment or {}
    roles = list(role_assignment.get("roles") or [])
    profiles: list[str] = []

    for role in roles:
        if role in _SERVICE_ROLES:
            profiles.append(role)

    env_lines: list[str] = []
    env_lines.append(f"COMPOSE_PROFILES={','.join(profiles)}")

    # DNS group config — only populated when a DNS role is assigned.
    dns_group_name = role_assignment.get("dns_group_name")
    dns_engine = role_assignment.get("dns_engine")
    if any(r in roles for r in ("dns-bind9", "dns-powerdns")):
        if dns_group_name:
            env_lines.append(f"AGENT_GROUP={dns_group_name}")
        if dns_engine:
            env_lines.append(f"DNS_ENGINE={dns_engine}")

    # DHCP group config.
    dhcp_group_name = role_assignment.get("dhcp_group_name")
    dhcp_network_mode = role_assignment.get("dhcp_network_mode") or "host"
    if "dhcp" in roles:
        if dhcp_group_name:
            # AGENT_GROUP is overloaded — DNS + DHCP can't be in the
            # same group anyway (different drivers), so when both
            # roles are assigned we still write one AGENT_GROUP and
            # let the compose templates per-role override via
            # role-specific env vars (Wave C3 reshape; for now we
            # emit a second AGENT_GROUP line — the later wins under
            # docker-compose's env-file parser).
            env_lines.append(f"DHCP_AGENT_GROUP={dhcp_group_name}")
        env_lines.append(f"DHCP_NETWORK_MODE={dhcp_network_mode}")

    return TargetEnv(env_lines=env_lines, profiles=profiles)


def render_env_file(target: TargetEnv, header: str | None = None) -> str:
    """Format a TargetEnv as a docker-compose env-file. Includes a
    ``# generated by spatium-supervisor`` header by default so the
    operator inspecting the file knows it shouldn't be hand-edited
    (every heartbeat overwrites)."""
    lines: list[str] = []
    if header:
        lines.append(header.rstrip("\n"))
    else:
        lines.append("# Auto-generated by spatium-supervisor — do not hand-edit.")
        lines.append("# Overwritten on every supervisor heartbeat that returns a")
        lines.append("# role_assignment block from the control plane.")
    lines.extend(target.env_lines)
    return "\n".join(lines) + "\n"


# ── DHCP bridged-mode port-conflict pre-flight (#170 Phase E2) ────


@dataclass(frozen=True)
class PortConflict:
    """Result of probing for a competing UDP/67 listener on the host.

    ``users`` is the raw text of the matching ``ss`` users field (the
    process or socket-owner string), surfaced to the operator so they
    know which daemon to kill before flipping bridged DHCP on.
    """

    port: int
    users: str


# Match ``users:(...)`` field that ss appends with -p; falls back to
# the local-address column when ss was invoked without -p (root or
# CAP_NET_ADMIN is needed for -p to populate process names).
_SS_USERS_RE = re.compile(r"users:\((.+?)\)")


# Service ports the supervisor probes on every heartbeat. Maps the
# heartbeat-body key the control plane stores back into
# ``appliance.port_conflicts`` to a (proto, port) tuple. DNS binds
# UDP+TCP/53 on the host's network namespace regardless of role
# orchestration (the dns-bind9 / dns-powerdns service container uses
# network_mode: host); DHCP binds UDP/67 on host either via network_
# mode: host (default) or bridged-mode port-mapping.
_PROBE_PORTS: dict[str, tuple[str, int]] = {
    "udp_53": ("udp", 53),
    "tcp_53": ("tcp", 53),
    "udp_67": ("udp", 67),
}


def detect_port_conflict(
    proto: str,
    port: int,
    *,
    ss_argv: list[str] | None = None,
) -> PortConflict | None:
    """Return a :class:`PortConflict` if something is already listening
    on ``proto`` ``port`` on the host. ``None`` means the port is free
    or ``ss`` is unavailable.

    The supervisor calls this every heartbeat for UDP+TCP/53 and
    UDP/67 — the ports DNS-BIND9 / DNS-PowerDNS / DHCP-Kea each bind
    on the host's network namespace. When a conflict exists the
    operator should know *before* assigning the service role,
    otherwise the role-switch lands in a state where the supervisor
    has scheduled the service but the container's bind silently
    loses to whatever pre-existing daemon owned the port.

    ``ss`` lives at ``/usr/sbin/ss`` on Debian; runs in the supervisor
    container's PID namespace via the host bind-mount the supervisor
    compose entry should expose. When ``ss`` is missing entirely (dev
    laptop, or a stripped image), return ``None`` rather than refuse —
    the host-side compose lifecycle will still surface the bind error
    if there genuinely is a conflict.
    """
    if proto not in ("udp", "tcp"):
        raise ValueError(f"unsupported proto {proto!r}")
    if shutil.which("ss") is None:
        return None
    # ``-uln`` / ``-tln`` per proto; ``-p`` adds users field (best-
    # effort, needs root); ``sport = :<port>`` narrows the kernel
    # filter so the output is small.
    flag = "-uln" if proto == "udp" else "-tln"
    argv = ss_argv or ["ss", flag, "-p", f"sport = :{port}"]
    try:
        result = subprocess.run(
            argv,
            capture_output=True,
            text=True,
            timeout=5,
        )
    except (FileNotFoundError, subprocess.TimeoutExpired):
        return None
    if result.returncode != 0:
        return None
    # ss output: header line then one row per listener. The local-
    # address column is field index 4 on UDP rows (5 fields:
    # NetidState Recv-Q Send-Q LocalAddr PeerAddr) and field index 4
    # on TCP rows too (same shape with State in field 1).
    needle = f":{port}"
    matches: list[str] = []
    for line in result.stdout.splitlines()[1:]:
        if needle not in line:
            continue
        parts = line.split()
        if len(parts) < 5:
            continue
        local = parts[3] if proto == "udp" else parts[3]
        if not local.endswith(needle):
            continue
        users_match = _SS_USERS_RE.search(line)
        matches.append(users_match.group(1) if users_match else local)
    if not matches:
        return None
    return PortConflict(port=port, users="; ".join(matches))


def probe_port_conflicts() -> dict[str, str]:
    """Probe every port in :data:`_PROBE_PORTS`. Returns a dict keyed
    by the heartbeat-body field name (``udp_53`` / ``tcp_53`` /
    ``udp_67``) with the conflicting users string as the value. Ports
    that are free / unprobed are omitted from the dict — empty result
    means "no conflicts detected". The supervisor's heartbeat sends
    this verbatim; the control plane persists it as
    ``appliance.port_conflicts``.
    """
    out: dict[str, str] = {}
    for key, (proto, port) in _PROBE_PORTS.items():
        conflict = detect_port_conflict(proto, port)
        if conflict is not None:
            out[key] = conflict.users
    return out


__all__ = [
    "TargetEnv",
    "compute_target_env",
    "render_env_file",
    "PortConflict",
    "detect_port_conflict",
    "probe_port_conflicts",
]
