import { useEffect, useState } from "react";
import { useMutation, useQuery } from "@tanstack/react-query";
import {
  Activity,
  AlertCircle,
  CheckCircle2,
  Download,
  FileText,
  PlayCircle,
  RefreshCw,
  ScrollText,
  XCircle,
} from "lucide-react";

import {
  applianceDiagnosticsApi,
  type ApplianceSelfTestReport,
} from "@/lib/api";

/**
 * Logs & Diagnostics (Phase 4e, rewritten as Phase 11 wave 4).
 *
 * Three operator-facing surfaces:
 *  - Log viewer: pick a host log file from the list, see the last 500
 *    lines, refresh on demand. Plain text, monospaced. Empty when no
 *    host bind mount is present (off-appliance + agent-only installs).
 *  - Self-test: one button, runs the battery server-side (DNS, kubeapi
 *    reachability, pod health, informational role presence) and renders
 *    the report inline. Latest run is preserved in component state.
 *  - Diagnostic bundle: one-click download of the zip generated by the
 *    api — logs + per-pod log tails (via kubeapi) + system info +
 *    redacted env.
 */
export function LogsTab() {
  return (
    <div className="mx-auto max-w-4xl space-y-4">
      <div>
        <h2 className="flex items-center gap-2 text-base font-semibold">
          <ScrollText className="h-4 w-4 text-muted-foreground" />
          Logs &amp; Diagnostics
        </h2>
        <p className="mt-1 text-xs text-muted-foreground">
          Host-side logs the appliance can reach, a one-click health check, and
          a redacted diagnostic bundle for sharing with support.
        </p>
      </div>

      <SelfTestCard />
      <LogViewerCard />
      <DiagnosticBundleCard />
    </div>
  );
}

// ── Self-test card ─────────────────────────────────────────────────

function SelfTestCard() {
  const [report, setReport] = useState<ApplianceSelfTestReport | null>(null);

  const run = useMutation({
    mutationFn: applianceDiagnosticsApi.selfTest,
    onSuccess: (r) => setReport(r),
  });

  return (
    <section className="rounded-lg border bg-card p-4 shadow-sm">
      <div className="flex items-start justify-between gap-3">
        <div>
          <h3 className="flex items-center gap-1.5 text-sm font-semibold">
            <Activity className="h-3.5 w-3.5 text-muted-foreground" />
            Self-test
          </h3>
          <p className="mt-0.5 text-[11px] text-muted-foreground">
            Runs five checks: external DNS resolution, kubeapi reachability
            via the api pod's ServiceAccount, every spatium pod's health
            (Running + healthy, Succeeded Jobs OK), and informational role
            presence (DHCP / DNS — OK when not assigned to this appliance).
          </p>
        </div>
        <button
          type="button"
          onClick={() => run.mutate()}
          disabled={run.isPending}
          className="inline-flex shrink-0 items-center gap-1 rounded-md bg-primary px-3 py-1.5 text-sm font-medium text-primary-foreground hover:bg-primary/90 disabled:opacity-50"
        >
          <PlayCircle className="h-3.5 w-3.5" />
          {run.isPending ? "Running…" : "Run check"}
        </button>
      </div>

      {run.isError && (
        <div className="mt-3 flex items-start gap-2 rounded-md border border-destructive/50 bg-destructive/10 p-2 text-xs text-destructive">
          <AlertCircle className="mt-0.5 h-3.5 w-3.5 shrink-0" />
          <span>{(run.error as Error).message}</span>
        </div>
      )}

      {report && (
        <div className="mt-3 space-y-1">
          <div className="flex items-center gap-2 text-xs">
            <span
              className={`inline-flex items-center gap-1 rounded-full px-1.5 py-0.5 text-[10px] font-medium uppercase tracking-wide ${
                report.overall_ok
                  ? "bg-emerald-500/10 text-emerald-700 dark:text-emerald-400"
                  : "bg-destructive/15 text-destructive"
              }`}
            >
              {report.overall_ok ? (
                <CheckCircle2 className="h-3 w-3" />
              ) : (
                <XCircle className="h-3 w-3" />
              )}
              {report.overall_ok ? "PASS" : "FAIL"}
            </span>
            <span className="text-muted-foreground">
              {new Date(report.run_at).toLocaleString()}
            </span>
          </div>
          <ul className="mt-1 space-y-1">
            {report.checks.map((c) => (
              <li
                key={c.name}
                className="flex items-start gap-2 rounded-md border bg-background px-2 py-1 text-xs"
              >
                {c.ok ? (
                  <CheckCircle2 className="mt-0.5 h-3.5 w-3.5 shrink-0 text-emerald-500" />
                ) : (
                  <XCircle className="mt-0.5 h-3.5 w-3.5 shrink-0 text-destructive" />
                )}
                <div className="min-w-0 flex-1">
                  <div className="font-medium">{c.name}</div>
                  <div className="font-mono text-[11px] text-muted-foreground">
                    {c.detail}
                  </div>
                </div>
              </li>
            ))}
          </ul>
        </div>
      )}
    </section>
  );
}

// ── Log viewer card ─────────────────────────────────────────────────

function LogViewerCard() {
  const [selected, setSelected] = useState<string | null>(null);

  const sources = useQuery({
    queryKey: ["appliance", "diagnostics", "logs"],
    queryFn: applianceDiagnosticsApi.listLogs,
  });

  useEffect(() => {
    if (!selected && sources.data && sources.data.sources.length > 0) {
      setSelected(sources.data.sources[0]);
    }
  }, [selected, sources.data]);

  const tail = useQuery({
    queryKey: ["appliance", "diagnostics", "logs", selected],
    queryFn: () =>
      selected
        ? applianceDiagnosticsApi.tailLog(selected, 500)
        : Promise.resolve(null),
    enabled: !!selected,
  });

  return (
    <section className="rounded-lg border bg-card p-4 shadow-sm">
      <div className="flex items-start justify-between gap-3">
        <h3 className="flex items-center gap-1.5 text-sm font-semibold">
          <FileText className="h-3.5 w-3.5 text-muted-foreground" />
          Host log viewer
        </h3>
        <button
          type="button"
          onClick={() => tail.refetch()}
          disabled={!selected || tail.isFetching}
          className="inline-flex items-center gap-1 rounded-md border bg-background px-2 py-1 text-xs hover:bg-accent disabled:opacity-50"
        >
          <RefreshCw
            className={`h-3 w-3 ${tail.isFetching ? "animate-spin" : ""}`}
          />
          Refresh
        </button>
      </div>

      <div className="mt-3 flex flex-wrap gap-1.5">
        {sources.data?.sources.map((name) => (
          <button
            key={name}
            type="button"
            onClick={() => setSelected(name)}
            className={`rounded-md border px-2 py-1 text-xs font-mono ${
              selected === name
                ? "border-primary bg-primary/10 text-foreground"
                : "bg-background hover:bg-accent"
            }`}
          >
            {name}
          </button>
        ))}
        {sources.data?.sources.length === 0 && (
          <span className="text-xs text-muted-foreground">
            No log files yet — appliance hasn't done much.
          </span>
        )}
      </div>

      <pre className="mt-3 max-h-96 overflow-auto rounded-md border bg-muted/30 px-3 py-2 font-mono text-[11px] leading-tight">
        {tail.isLoading
          ? "Loading…"
          : tail.isError
            ? `(error: ${(tail.error as Error).message})`
            : tail.data?.tail || "(empty)"}
      </pre>
    </section>
  );
}

// ── Diagnostic bundle card ──────────────────────────────────────────

function DiagnosticBundleCard() {
  return (
    <section className="rounded-lg border bg-card p-4 shadow-sm">
      <div className="flex items-start justify-between gap-3">
        <div>
          <h3 className="flex items-center gap-1.5 text-sm font-semibold">
            <Download className="h-3.5 w-3.5 text-muted-foreground" />
            Diagnostic bundle
          </h3>
          <p className="mt-0.5 text-[11px] text-muted-foreground">
            One-click zip of host logs, per-pod log tails (last 500 lines
            each via kubeapi), system info, and a redacted env dump. Useful
            for support tickets. Secrets (passwords, tokens, keys) are
            stripped before bundling.
          </p>
        </div>
        <a
          href={applianceDiagnosticsApi.bundleUrl()}
          className="inline-flex shrink-0 items-center gap-1 rounded-md border bg-background px-3 py-1.5 text-sm hover:bg-accent"
        >
          <Download className="h-3.5 w-3.5" />
          Download bundle
        </a>
      </div>
    </section>
  );
}
