"""Server-side firewall render (#285 Phase 2a) — pure-function tests.

The load-bearing one is ``test_byte_identical_with_supervisor_renderer``:
``compile_firewall_body`` is a verbatim port of the supervisor's in-pod
``render_drop_in`` and MUST produce a byte-identical body, else a node's
drop-in changes hash purely on which renderer ran. These are pure (no DB)
so they run on the host venv; the identity test loads the supervisor
renderer standalone via importlib and skips if it isn't on disk (e.g. a
backend-only container mount).
"""

from __future__ import annotations

import hashlib
import importlib.util
import pathlib
import sys

import pytest

from app.services.appliance.firewall import compile_firewall_body, firewall_bundle

# The full input matrix the byte-identity + smoke tests exercise.
_MATRIX: list[dict] = [
    {"role_assignment": {"roles": []}},  # idle
    {"role_assignment": {"roles": ["dns-bind9"]}},
    {"role_assignment": {"roles": ["dhcp"]}},
    {"role_assignment": {"roles": ["dns-powerdns", "dhcp"]}},
    # single-node CP: pod/service CIDR, no peers
    {
        "role_assignment": {"roles": []},
        "pod_cidrs": ["10.42.0.0/16"],
        "service_cidrs": ["10.43.0.0/16"],
    },
    # multi-node CP + VIP: peers, pod, svc, memberlist
    {
        "role_assignment": {"roles": ["dns-bind9"], "kubeapi_expose_cidrs": ["10.9.0.0/24"]},
        "cluster_peer_cidrs": ["192.168.0.133/32", "192.168.0.125/32"],
        "pod_cidrs": ["10.42.0.0/16"],
        "service_cidrs": ["10.43.0.0/16"],
        "cp_member_count": 3,
        "vip_configured": True,
    },
    # dual-stack peers
    {
        "role_assignment": {"roles": []},
        "cluster_peer_cidrs": ["192.168.0.10", "2001:db8::10", "2001:db8::11/128"],
        "pod_cidrs": ["10.42.0.0/16", "2001:cafe:42::/56"],
        "cp_member_count": 2,
    },
    # operator firewall_extra
    {"role_assignment": {"roles": ["dhcp"], "firewall_extra": 'udp dport 161 accept comment "x"'}},
]


def _call(fn, case: dict):
    ra = case["role_assignment"]
    peers = case.get("cluster_peer_cidrs")
    return fn(
        ra,
        peers,
        pod_cidrs=case.get("pod_cidrs"),
        service_cidrs=case.get("service_cidrs"),
        cp_member_count=case.get("cp_member_count", 1),
        vip_configured=case.get("vip_configured", False),
    )


def _load_supervisor_renderer():
    """Load the supervisor's firewall_renderer standalone (no intra-package
    imports; needs only structlog). Returns None if the file isn't present."""
    path = (
        pathlib.Path(__file__).resolve().parents[2]
        / "agent/supervisor/spatium_supervisor/firewall_renderer.py"
    )
    if not path.exists():
        return None
    spec = importlib.util.spec_from_file_location("_sup_firewall_renderer", path)
    assert spec and spec.loader
    mod = importlib.util.module_from_spec(spec)
    # The renderer defines a @dataclass; dataclasses resolves the class's
    # module via sys.modules, so register it before exec_module.
    sys.modules[spec.name] = mod
    spec.loader.exec_module(mod)
    return mod


def test_byte_identical_with_supervisor_renderer() -> None:
    sup = _load_supervisor_renderer()
    if sup is None:
        pytest.skip("supervisor firewall_renderer not on disk (backend-only checkout)")
    for case in _MATRIX:
        backend_body = _call(compile_firewall_body, case)
        supervisor_body = _call(sup.render_drop_in, case).body
        assert backend_body == supervisor_body, f"render drift for {case!r}"


def test_no_dataplane_rule_either_side() -> None:
    # Neither renderer may emit a flannel/wireguard INPUT rule (#285 — VXLAN
    # bypasses our chain). Guards against a one-sided data-plane-floor add.
    sup = _load_supervisor_renderer()
    for case in _MATRIX:
        body = _call(compile_firewall_body, case)
        assert "8472" not in body and "51820" not in body and "dataplane" not in body
        if sup is not None:
            assert "8472" not in _call(sup.render_drop_in, case).body


def test_bundle_disabled_shape() -> None:
    b = firewall_bundle(
        role_assignment={"roles": []},
        cluster_peer_cidrs=[],
        pod_cidrs=[],
        service_cidrs=[],
        cp_member_count=1,
        vip_configured=False,
        firewall_enabled=False,
    )
    assert b == {"enabled": False, "config_hash": "", "firewall_conf": ""}


def test_bundle_enabled_shape() -> None:
    b = firewall_bundle(
        role_assignment={"roles": ["dns-bind9"]},
        cluster_peer_cidrs=[],
        pod_cidrs=[],
        service_cidrs=[],
        cp_member_count=1,
        vip_configured=False,
        firewall_enabled=True,
    )
    assert b["enabled"] is True
    assert b["firewall_conf"].startswith("# Auto-generated by spatium-supervisor")
    assert "tcp dport 53 accept" in b["firewall_conf"]
    assert b["config_hash"] == hashlib.sha256(b["firewall_conf"].encode()).hexdigest()


def test_bundle_multinode_retire_directive() -> None:
    # cp_member_count >= 2 → the body carries the retire directive that drives
    # host-side sentinel retirement (Phase 1b).
    single = firewall_bundle(
        role_assignment={"roles": []},
        cluster_peer_cidrs=[],
        pod_cidrs=["10.42.0.0/16"],
        service_cidrs=[],
        cp_member_count=1,
        vip_configured=False,
        firewall_enabled=True,
    )
    multi = firewall_bundle(
        role_assignment={"roles": []},
        cluster_peer_cidrs=["192.168.0.2/32"],
        pod_cidrs=["10.42.0.0/16"],
        service_cidrs=[],
        cp_member_count=3,
        vip_configured=False,
        firewall_enabled=True,
    )
    assert "# spatium-bootstrap: keep" in single["firewall_conf"]
    assert "# spatium-bootstrap: retire" in multi["firewall_conf"]
