"""Heartbeat ships the server-rendered firewall block (#285 Phase 2a).

When ``platform_settings.firewall_enabled`` is on, the heartbeat response
carries a non-empty ``firewall_settings`` block and the handler persists
the rendered hash to FirewallApplyState (for 2d's drift/alarm). Default
off → disabled-shape block, no rendered_hash written (supervisor keeps its
in-pod fallback).
"""

from __future__ import annotations

import hashlib
import os
import uuid

from httpx import AsyncClient
from sqlalchemy.ext.asyncio import AsyncSession

from app.models.appliance import APPLIANCE_STATE_APPROVED, Appliance
from app.models.firewall import FirewallApplyState
from app.models.settings import PlatformSettings
from app.services.appliance.ca import generate_session_token


async def _approved(db: AsyncSession, *, firewall_enabled: bool) -> tuple[Appliance, str]:
    s = await db.get(PlatformSettings, 1)
    if s is None:
        s = PlatformSettings(id=1)
        db.add(s)
    s.supervisor_registration_enabled = True
    s.firewall_enabled = firewall_enabled
    token, token_hash = generate_session_token()
    der = os.urandom(32)
    row = Appliance(
        id=uuid.uuid4(),
        hostname="cp-1",
        public_key_der=der,
        public_key_fingerprint=hashlib.sha256(der).hexdigest(),
        state=APPLIANCE_STATE_APPROVED,
        deployment_kind="appliance",
        appliance_variant="control-plane",
        session_token_hash=token_hash,
    )
    db.add(row)
    await db.flush()
    return row, token


async def _hb(client: AsyncClient, row: Appliance, token: str) -> dict:
    r = await client.post(
        "/api/v1/appliance/supervisor/heartbeat",
        json={"appliance_id": str(row.id), "session_token": token},
    )
    assert r.status_code == 200, r.text
    return r.json()


async def test_enabled_ships_block_and_persists_rendered_hash(
    client: AsyncClient, db_session: AsyncSession
) -> None:
    row, token = await _approved(db_session, firewall_enabled=True)
    await db_session.commit()

    body = await _hb(client, row, token)
    fw = body["firewall_settings"]
    assert fw["enabled"] is True
    assert fw["config_hash"]
    assert fw["firewall_conf"].startswith("# Auto-generated by spatium-supervisor")
    # control-plane variant → runs the apiserver → 6443 rule present once a
    # pod CIDR is known; at minimum the mgmt floor + a hash are rendered.
    assert fw["config_hash"] == hashlib.sha256(fw["firewall_conf"].encode()).hexdigest()

    db_session.expunge_all()
    st = await db_session.get(FirewallApplyState, row.id)
    assert st is not None
    assert st.rendered_hash == fw["config_hash"]
    assert st.last_rendered_at is not None


async def test_disabled_ships_empty_block_no_rendered_hash(
    client: AsyncClient, db_session: AsyncSession
) -> None:
    row, token = await _approved(db_session, firewall_enabled=False)
    await db_session.commit()

    body = await _hb(client, row, token)
    fw = body["firewall_settings"]
    assert fw == {"enabled": False, "config_hash": "", "firewall_conf": ""}

    db_session.expunge_all()
    # No authoritative render → no rendered_hash row created by this path.
    st = await db_session.get(FirewallApplyState, row.id)
    assert st is None or st.rendered_hash is None
