"""Operator Copilot tools for the fleet firewall (#285 Phase 3e).

Registration metadata (module tag + default-enabled state) + behaviour:
reads return data, the propose write produces a proposal, the superadmin gate
holds, find_firewall_effective renders a node's merged body.
"""

from __future__ import annotations

import hashlib
import os
import uuid

from sqlalchemy.ext.asyncio import AsyncSession

from app.models.appliance import APPLIANCE_STATE_APPROVED, Appliance
from app.models.auth import User
from app.models.firewall import FirewallPolicy, FirewallRule
from app.services.ai.tools import firewall as fw
from app.services.ai.tools.base import REGISTRY
from app.services.appliance.firewall_merge import reset_policy_cache

READ_TOOLS = [
    "find_firewall_policies",
    "count_firewall_policies",
    "find_firewall_aliases",
    "find_firewall_effective",
    "find_web_ui_access",
]


async def _user(db: AsyncSession, *, superadmin: bool) -> User:
    u = User(
        username=f"u-{uuid.uuid4().hex[:8]}",
        email=f"{uuid.uuid4().hex[:8]}@x.com",
        display_name="T",
        hashed_password="x",
        is_superadmin=superadmin,
    )
    db.add(u)
    await db.flush()
    return u


def test_registration_metadata() -> None:
    for name in READ_TOOLS:
        t = REGISTRY.get(name)
        assert t is not None, name
        assert t.module == "appliance.firewall"
        assert t.default_enabled is True
    propose = REGISTRY.get("propose_toggle_firewall_policy")
    assert propose is not None
    assert propose.module == "appliance.firewall"
    # Broad-blast-radius write → opt-in (default-disabled).
    assert propose.default_enabled is False


async def test_non_superadmin_blocked(db_session: AsyncSession) -> None:
    u = await _user(db_session, superadmin=False)
    res = await fw.find_firewall_policies(db_session, u, fw.FindFirewallPoliciesArgs())
    assert "error" in res and "superadmin" in res["error"]


async def test_find_and_count_policies(db_session: AsyncSession) -> None:
    u = await _user(db_session, superadmin=True)
    p = FirewallPolicy(name="dns", scope_kind="role", scope_role="dns-bind9", enabled=True)
    db_session.add(p)
    await db_session.flush()
    db_session.add(
        FirewallRule(policy_id=p.id, seq=10, action="accept", protocol="udp", ports=[53])
    )
    db_session.add(FirewallPolicy(name="off", scope_kind="role", scope_role="dhcp", enabled=False))
    await db_session.flush()

    listing = await fw.find_firewall_policies(db_session, u, fw.FindFirewallPoliciesArgs())
    names = {p["name"] for p in listing["policies"]}
    assert {"dns", "off"} <= names
    dns = next(x for x in listing["policies"] if x["name"] == "dns")
    assert any("accept udp 53 from any" in r for r in dns["rules"])

    counts = await fw.count_firewall_policies(db_session, u, fw.CountFirewallPoliciesArgs())
    assert counts["total"] == 2
    assert counts["disabled"] == 1
    assert counts["by_scope_kind"].get("role") == 2

    # scope filter
    only_dhcp = await fw.find_firewall_policies(
        db_session, u, fw.FindFirewallPoliciesArgs(scope_role="dhcp")
    )
    assert {p["name"] for p in only_dhcp["policies"]} == {"off"}


async def test_find_effective_renders_body(db_session: AsyncSession) -> None:
    reset_policy_cache()
    u = await _user(db_session, superadmin=True)
    der = os.urandom(32)
    a = Appliance(
        id=uuid.uuid4(),
        hostname="fw-node",
        public_key_der=der,
        public_key_fingerprint=hashlib.sha256(der).hexdigest(),
        state=APPLIANCE_STATE_APPROVED,
        deployment_kind="appliance",
        appliance_variant="control-plane",
        pod_cidr="10.42.0.0/16",
        service_cidr="10.43.0.0/16",
    )
    db_session.add(a)
    await db_session.flush()
    res = await fw.find_firewall_effective(
        db_session, u, fw.FindFirewallEffectiveArgs(appliance_id=str(a.id))
    )
    assert res["hostname"] == "fw-node"
    assert res["firewall_conf"].startswith("# Auto-generated by spatium-supervisor")
    assert res["firewall_enabled"] is False  # no PlatformSettings row → dark


async def test_find_effective_bad_uuid(db_session: AsyncSession) -> None:
    u = await _user(db_session, superadmin=True)
    res = await fw.find_firewall_effective(
        db_session, u, fw.FindFirewallEffectiveArgs(appliance_id="not-a-uuid")
    )
    assert "error" in res


async def test_find_web_ui_access(db_session: AsyncSession) -> None:
    from app.models.settings import PlatformSettings

    u = await _user(db_session, superadmin=True)
    # Default (no row) → open.
    res = await fw.find_web_ui_access(db_session, u, fw.FindWebUIAccessArgs())
    assert res["open"] is True and res["allowed_cidrs"] == []
    # Scoped.
    db_session.add(PlatformSettings(id=1, web_ui_allowed_cidrs=["192.168.0.0/24"]))
    await db_session.flush()
    res2 = await fw.find_web_ui_access(db_session, u, fw.FindWebUIAccessArgs())
    assert res2["open"] is False and res2["allowed_cidrs"] == ["192.168.0.0/24"]
    # Gated.
    v = await _user(db_session, superadmin=False)
    res3 = await fw.find_web_ui_access(db_session, v, fw.FindWebUIAccessArgs())
    assert "error" in res3 and "superadmin" in res3["error"]


async def test_propose_toggle_policy(db_session: AsyncSession) -> None:
    u = await _user(db_session, superadmin=True)
    p = FirewallPolicy(name="cp", scope_kind="role", scope_role="control-plane", enabled=True)
    db_session.add(p)
    await db_session.flush()
    # valid toggle (enabled True → False) → a proposal, not a rejection
    res = await fw.propose_toggle_firewall_policy(
        db_session, u, fw.ProposeToggleFirewallPolicyArgs(policy_id=str(p.id), enabled=False)
    )
    assert res.get("kind") != "proposal_rejected", res
    # no-op toggle (already enabled) → rejected at preview
    res2 = await fw.propose_toggle_firewall_policy(
        db_session, u, fw.ProposeToggleFirewallPolicyArgs(policy_id=str(p.id), enabled=True)
    )
    assert res2.get("kind") == "proposal_rejected"
