"""Effective fleet-firewall render endpoint (#285 Phase 3c-2).

GET /appliance/firewall/appliances/{id}/effective server-renders a node's
merged drop-in via the SAME merge the heartbeat uses (re-deriving inputs with
supervisor.firewall_render_inputs), returns the layer breakdown + apply-state
drift, and works regardless of firewall_enabled (dark-state preview).
"""

from __future__ import annotations

import hashlib
import os
import uuid

import pytest
from httpx import AsyncClient
from sqlalchemy.ext.asyncio import AsyncSession

from app.core.security import create_access_token, hash_password
from app.models.appliance import APPLIANCE_STATE_APPROVED, Appliance
from app.models.auth import User
from app.models.firewall import FirewallPolicy, FirewallRule
from app.services.appliance.firewall_merge import reset_policy_cache
from app.services.feature_modules import invalidate_cache

FW = "/api/v1/appliance/firewall"


@pytest.fixture(autouse=True)
def _reset_caches():
    reset_policy_cache()
    invalidate_cache()
    yield
    reset_policy_cache()
    invalidate_cache()


async def _admin(db: AsyncSession) -> dict:
    u = User(
        username=f"u-{uuid.uuid4().hex[:8]}",
        email=f"{uuid.uuid4().hex[:8]}@x.com",
        display_name="T",
        hashed_password=hash_password("x"),
        is_superadmin=True,
    )
    db.add(u)
    await db.flush()
    return {"Authorization": f"Bearer {create_access_token(str(u.id))}"}


async def _appliance(db: AsyncSession, *, variant: str = "application", **kw) -> Appliance:
    der = os.urandom(32)
    a = Appliance(
        id=uuid.uuid4(),
        hostname=f"n-{uuid.uuid4().hex[:6]}",
        public_key_der=der,
        public_key_fingerprint=hashlib.sha256(der).hexdigest(),
        state=APPLIANCE_STATE_APPROVED,
        deployment_kind="appliance",
        appliance_variant=variant,
        **kw,
    )
    db.add(a)
    await db.flush()
    return a


async def test_effective_404_unknown(client: AsyncClient, db_session: AsyncSession) -> None:
    h = await _admin(db_session)
    r = await client.get(f"{FW}/appliances/{uuid.uuid4()}/effective", headers=h)
    assert r.status_code == 404


async def test_effective_control_plane_body_and_layers(
    client: AsyncClient, db_session: AsyncSession
) -> None:
    h = await _admin(db_session)
    a = await _appliance(
        db_session, variant="control-plane", pod_cidr="10.42.0.0/16", service_cidr="10.43.0.0/16"
    )
    await db_session.commit()
    r = await client.get(f"{FW}/appliances/{a.id}/effective", headers=h)
    assert r.status_code == 200, r.text
    j = r.json()
    assert j["firewall_conf"].startswith("# Auto-generated by spatium-supervisor")
    assert j["config_hash"] == hashlib.sha256(j["firewall_conf"].encode()).hexdigest()
    # mgmt floor always present; control-plane derived present (is_cp via pod/svc)
    assert any("dport 22 accept" in ln for ln in j["layers"]["management"])
    assert j["layers"]["control_plane"], j["layers"]
    # default platform settings → enforcement off (dark preview still renders)
    assert j["firewall_enabled"] is False
    assert j["drift"] is False


async def test_effective_reflects_operator_fleet_rule(
    client: AsyncClient, db_session: AsyncSession
) -> None:
    h = await _admin(db_session)
    a = await _appliance(db_session)  # idle → only mgmt + overlay
    # seed a fleet policy + operator rule directly
    p = FirewallPolicy(name="fleet", scope_kind="fleet", enabled=True)
    db_session.add(p)
    await db_session.flush()
    db_session.add(
        FirewallRule(
            policy_id=p.id, seq=10, action="accept", protocol="udp", ports=[514], comment="syslog"
        )
    )
    await db_session.commit()
    reset_policy_cache()
    r = await client.get(f"{FW}/appliances/{a.id}/effective", headers=h)
    assert r.status_code == 200, r.text
    assert 'udp dport 514 accept comment "syslog"' in r.json()["layers"]["overlay"]
