#!/usr/bin/env bash
# Codespaces post-create bootstrap. Runs once when a fresh Codespace
# is built. Brings up the SpatiumDDI stack from source (so the demo
# always reflects the branch the Codespace was created from), waits
# for the API, then seeds realistic demo data.
#
# Locked-down by DEMO_MODE=1 in the generated .env — see
# backend/app/core/demo_mode.py for the full list of disabled
# surfaces. The visitor signs in with admin / admin.

set -euo pipefail

cd "$(dirname "$0")/.."

echo "── Generating .env (DEMO_MODE=1) ──"
if [[ ! -f .env ]]; then
  POSTGRES_PW=$(openssl rand -hex 24)
  SECRET=$(openssl rand -hex 32)
  cat > .env <<EOF
# Auto-generated by .devcontainer/post-create.sh.
# Do not commit — this file is in .gitignore.

POSTGRES_PASSWORD=${POSTGRES_PW}
SECRET_KEY=${SECRET}
CREDENTIAL_ENCRYPTION_KEY=${SECRET}

# Demo lockdown — see backend/app/core/demo_mode.py
DEMO_MODE=1

# Lab-only agent keys; no agents are started in the Codespace demo
# but the api still needs the env vars to validate.
DNS_AGENT_KEY=demo-dns-agent-key
DHCP_AGENT_KEY=demo-dhcp-agent-key
EOF
fi

echo "── Building images from source (5–8 min on a 4-core Codespace) ──"
docker compose \
  -f docker-compose.yml \
  -f docker-compose.dev.yml \
  build api worker beat frontend migrate

echo "── Running migrations ──"
docker compose \
  -f docker-compose.yml \
  -f docker-compose.dev.yml \
  run --rm migrate

echo "── Starting the stack ──"
docker compose \
  -f docker-compose.yml \
  -f docker-compose.dev.yml \
  up -d postgres redis api worker beat frontend

echo "── Waiting for API readiness ──"
for i in {1..60}; do
  if curl -fsS http://localhost:8000/health/live >/dev/null 2>&1; then
    echo "API is up."
    break
  fi
  if [[ $i -eq 60 ]]; then
    echo "API didn't come up in 60s — check 'docker compose logs api'." >&2
    exit 1
  fi
  sleep 1
done

echo "── Seeding demo data ──"
python3 -m pip install --quiet --user httpx
python3 scripts/seed_demo.py http://localhost:8000 admin admin || \
  echo "(seed exited non-zero — usually means data already present; safe to ignore)"

echo
echo "──────────────────────────────────────────────────────────────"
echo " SpatiumDDI demo is ready."
echo "  • UI:    forwarded as port 8077 (will auto-open)"
echo "  • Login: admin / admin  (locked by DEMO_MODE)"
echo "──────────────────────────────────────────────────────────────"
