"""e911 dispatchable location — ERLs, bindings, resolution log (#972)

Three tables for the Location Information Server core. Hand-written
rather than shipped as autogenerated: ``--autogenerate`` against this
schema also emits ~200 spurious drops (indexes and constraints created
by hand-written migrations that model metadata does not declare), and
committing those would drop live indexes across a dozen unrelated
tables. Only the e911 statements are kept.

``emergency_response_location`` is wide by design — 31 of its columns are
the RFC 5139 civic-address elements, one per element, because PIDF-LO and
every provider validation API want them separately and a single address
string cannot be decomposed later. See ``app.models.e911``.

No backfill: there is nothing to derive an ERL from. An install upgrades
into this feature with zero ERLs, every resolution answers
``confidence="none"``, and the ``e911_voice_subnet_unbound`` conformity
check is what tells the operator there is work to do.

Revision ID: c1f4a90e7d63
Revises: f7c3a91e50b4
"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = "c1f4a90e7d63"
down_revision = "f7c3a91e50b4"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.create_table('emergency_response_location',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('site_id', sa.UUID(), nullable=True),
    sa.Column('country', sa.String(length=2), nullable=True),
    sa.Column('a1', sa.String(length=255), nullable=True),
    sa.Column('a2', sa.String(length=255), nullable=True),
    sa.Column('a3', sa.String(length=255), nullable=True),
    sa.Column('a4', sa.String(length=255), nullable=True),
    sa.Column('a5', sa.String(length=255), nullable=True),
    sa.Column('a6', sa.String(length=255), nullable=True),
    sa.Column('prd', sa.String(length=64), nullable=True),
    sa.Column('pod', sa.String(length=64), nullable=True),
    sa.Column('sts', sa.String(length=64), nullable=True),
    sa.Column('hno', sa.String(length=64), nullable=True),
    sa.Column('hns', sa.String(length=64), nullable=True),
    sa.Column('lmk', sa.String(length=255), nullable=True),
    sa.Column('loc', sa.String(length=255), nullable=True),
    sa.Column('nam', sa.String(length=255), nullable=True),
    sa.Column('pc', sa.String(length=32), nullable=True),
    sa.Column('bld', sa.String(length=255), nullable=True),
    sa.Column('unit', sa.String(length=64), nullable=True),
    sa.Column('flr', sa.String(length=64), nullable=True),
    sa.Column('room', sa.String(length=64), nullable=True),
    sa.Column('plc', sa.String(length=64), nullable=True),
    sa.Column('pcn', sa.String(length=255), nullable=True),
    sa.Column('pobox', sa.String(length=64), nullable=True),
    sa.Column('addcode', sa.String(length=64), nullable=True),
    sa.Column('seat', sa.String(length=64), nullable=True),
    sa.Column('rd', sa.String(length=255), nullable=True),
    sa.Column('rdsec', sa.String(length=255), nullable=True),
    sa.Column('rdbr', sa.String(length=255), nullable=True),
    sa.Column('rdsubbr', sa.String(length=255), nullable=True),
    sa.Column('prm', sa.String(length=64), nullable=True),
    sa.Column('pom', sa.String(length=64), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('altitude', sa.Numeric(precision=9, scale=2), nullable=True),
    sa.Column('altitude_unit', sa.String(length=8), nullable=True),
    sa.Column('elins', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('validation_state', sa.String(length=16), server_default='unvalidated', nullable=False),
    sa.Column('validated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('validation_source', sa.String(length=64), nullable=True),
    sa.Column('validation_detail', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('notes', sa.Text(), server_default='', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('modified_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("validation_state IN ('unvalidated', 'validated', 'rejected')", name='ck_erl_validation_state'),
    sa.CheckConstraint('num_nonnulls(latitude, longitude) IN (0, 2)', name='ck_erl_point_is_complete'),
    sa.ForeignKeyConstraint(['site_id'], ['site.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', name='uq_erl_name')
    )
    op.create_index('ix_erl_site_id', 'emergency_response_location', ['site_id'], unique=False)
    op.create_table('e911_resolution_log',
    sa.Column('queried_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('identity_kind', sa.String(length=16), nullable=False),
    sa.Column('identity_value', sa.String(length=255), nullable=False),
    sa.Column('actor_kind', sa.String(length=16), nullable=False),
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('source_ip', postgresql.INET(), nullable=True),
    sa.Column('erl_id', sa.UUID(), nullable=True),
    sa.Column('rule_matched', sa.String(length=16), nullable=True),
    sa.Column('confidence', sa.String(length=16), nullable=False),
    sa.Column('degraded_reason', sa.Text(), nullable=True),
    sa.Column('evidence_age_seconds', sa.Integer(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['erl_id'], ['emergency_response_location.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_e911_res_log_actor', 'e911_resolution_log', ['actor_kind', 'actor_id'], unique=False)
    op.create_index('ix_e911_res_log_identity', 'e911_resolution_log', ['identity_kind', 'identity_value'], unique=False)
    op.create_index('ix_e911_res_log_queried_at', 'e911_resolution_log', ['queried_at'], unique=False)
    op.create_table('erl_binding',
    sa.Column('erl_id', sa.UUID(), nullable=False),
    sa.Column('rule_kind', sa.String(length=16), nullable=False),
    sa.Column('network_interface_id', sa.UUID(), nullable=True),
    sa.Column('bssid', sa.String(length=64), nullable=True),
    sa.Column('subnet_id', sa.UUID(), nullable=True),
    sa.Column('vlan_ref_id', sa.UUID(), nullable=True),
    sa.Column('mac_address', postgresql.MACADDR(), nullable=True),
    sa.Column('ip_address_id', sa.UUID(), nullable=True),
    sa.Column('site_id', sa.UUID(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('notes', sa.Text(), server_default='', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('modified_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(rule_kind = 'switch_port') = (network_interface_id IS NOT NULL) AND (rule_kind = 'wireless_ap') = (bssid IS NOT NULL) AND (rule_kind = 'subnet') = (subnet_id IS NOT NULL) AND (rule_kind = 'vlan') = (vlan_ref_id IS NOT NULL) AND (rule_kind = 'mac') = (mac_address IS NOT NULL) AND (rule_kind = 'ip') = (ip_address_id IS NOT NULL) AND (rule_kind = 'site_default') = (site_id IS NOT NULL)", name='ck_erl_binding_target_matches_kind'),
    sa.CheckConstraint("rule_kind IN ('switch_port', 'wireless_ap', 'subnet', 'vlan', 'mac', 'ip', 'site_default')", name='ck_erl_binding_rule_kind'),
    sa.CheckConstraint('num_nonnulls(network_interface_id, bssid, subnet_id, vlan_ref_id, mac_address, ip_address_id, site_id) = 1', name='ck_erl_binding_one_target'),
    sa.ForeignKeyConstraint(['erl_id'], ['emergency_response_location.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ip_address_id'], ['ip_address.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['network_interface_id'], ['network_interface.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['site_id'], ['site.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subnet_id'], ['subnet.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vlan_ref_id'], ['vlan.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bssid', name='uq_erl_binding_bssid'),
    sa.UniqueConstraint('ip_address_id', name='uq_erl_binding_ip'),
    sa.UniqueConstraint('mac_address', name='uq_erl_binding_mac'),
    sa.UniqueConstraint('network_interface_id', name='uq_erl_binding_interface'),
    sa.UniqueConstraint('site_id', name='uq_erl_binding_site'),
    sa.UniqueConstraint('subnet_id', name='uq_erl_binding_subnet'),
    sa.UniqueConstraint('vlan_ref_id', name='uq_erl_binding_vlan')
    )
    op.create_index('ix_erl_binding_erl_id', 'erl_binding', ['erl_id'], unique=False)
    op.create_index('ix_erl_binding_rule_kind', 'erl_binding', ['rule_kind'], unique=False)

    # Default-on, matching ``ModuleSpec.default_enabled`` for
    # ``network.e911``. Harmless on an install that never configures an
    # ERL: the surface is empty and every resolution says so.
    op.execute(sa.text("""
        INSERT INTO feature_module (id, enabled)
        VALUES ('network.e911', TRUE)
        ON CONFLICT (id) DO NOTHING
    """))


def downgrade() -> None:
    op.execute(sa.text("DELETE FROM feature_module WHERE id = 'network.e911'"))
    op.drop_index("ix_erl_binding_rule_kind", table_name="erl_binding")
    op.drop_index("ix_erl_binding_erl_id", table_name="erl_binding")
    op.drop_table("erl_binding")
    op.drop_index("ix_e911_res_log_queried_at", table_name="e911_resolution_log")
    op.drop_index("ix_e911_res_log_identity", table_name="e911_resolution_log")
    op.drop_index("ix_e911_res_log_actor", table_name="e911_resolution_log")
    op.drop_table("e911_resolution_log")
    op.drop_index("ix_erl_site_id", table_name="emergency_response_location")
    op.drop_table("emergency_response_location")
