#!/usr/bin/env bash
# dnsdist front entrypoint (issue #146 Phase 2).
#
# dnsdist runs as a SEPARATE container (its own netns) and forwards to the
# PowerDNS backend over the network at ${DNSDIST_BACKEND} (e.g.
# "dns-powerdns:53") — pdns never moves port. The base config (listen :53 +
# the backend) is built here from env; the operator's rate-limit RULES are
# rendered by the PowerDNS agent into ${RULES_FILE} (a shared, read-only
# volume) and appended. dnsdist has no clean full-config hot reload, so we
# supervise it and rebuild+restart whenever the rules file changes.
set -u

BACKEND="${DNSDIST_BACKEND:-dns-powerdns:53}"
RULES_FILE="${DNSDIST_RULES_FILE:-/agent-state/dnsdist-rules.conf}"
FULL_CONF="${DNSDIST_CONF:-/tmp/dnsdist.conf}"
POLL="${DNSDIST_POLL_SECONDS:-5}"
DNSDIST_BIN="$(command -v dnsdist)"

pid=""
last_sig=""

# dnsdist's newServer() needs an IP literal, not a hostname — resolve the
# backend host (e.g. "dns-powerdns:53") to "<ip>:<port>". A bare IP passes
# through getent unchanged. Echoes "" if the host can't be resolved yet.
resolve_backend() {
  local hostport="$1" host port ip
  host="${hostport%:*}"
  port="${hostport##*:}"
  [ "$host" = "$port" ] && port=53   # no ":port" given
  ip="$(getent hosts "$host" 2>/dev/null | awk '{print $1; exit}')"
  [ -n "$ip" ] && echo "${ip}:${port}"
}

build_conf() {
  local backend_ip="$1"
  {
    echo "-- generated by the SpatiumDDI dnsdist front entrypoint"
    echo "setLocal(\"0.0.0.0:53\")"
    echo "addLocal(\"[::]:53\")"
    echo "newServer({address=\"${backend_ip}\", name=\"pdns\"})"
    echo 'setACL({"0.0.0.0/0", "::/0"})'
    if [ -s "$RULES_FILE" ]; then
      cat "$RULES_FILE"
    fi
  } > "$FULL_CONF"
}

stop_dnsdist() {
  if [ -n "$pid" ] && kill -0 "$pid" 2>/dev/null; then
    kill "$pid" 2>/dev/null || true
    wait "$pid" 2>/dev/null || true
  fi
  pid=""
}

trap 'stop_dnsdist; exit 0' TERM INT

echo "dnsdist front: backend=${BACKEND}, rules=${RULES_FILE} (poll ${POLL}s)"
while true; do
  backend_ip="$(resolve_backend "$BACKEND")"
  if [ -z "$backend_ip" ]; then
    echo "dnsdist front: backend ${BACKEND} not resolvable yet; waiting" >&2
    sleep "$POLL"
    continue
  fi
  # Signature folds the resolved backend IP + the rules-file mtime, so a
  # rules change OR a backend IP drift triggers a rebuild + restart.
  rules_sig="none"
  [ -s "$RULES_FILE" ] && rules_sig="$(stat -c %Y "$RULES_FILE" 2>/dev/null || echo 0)"
  sig="${backend_ip}|${rules_sig}"
  if [ "$sig" != "$last_sig" ] || { [ -n "$pid" ] && ! kill -0 "$pid" 2>/dev/null; }; then
    build_conf "$backend_ip"
    if "$DNSDIST_BIN" --check-config -C "$FULL_CONF" >/dev/null 2>&1; then
      echo "dnsdist front: (re)loading (backend=$backend_ip rules=$rules_sig)"
      stop_dnsdist
      "$DNSDIST_BIN" --supervised --disable-syslog -C "$FULL_CONF" &
      pid="$!"
      last_sig="$sig"
    else
      echo "dnsdist front: rebuilt config failed --check-config; keeping current instance" >&2
      last_sig="$sig"
    fi
  fi
  sleep "$POLL"
done
