"""BIND9 archive importer (issue #128 Phase 1).

Pipeline:

1. Operator uploads a ``.zip`` or ``.tar(.gz|.bz2|.xz)`` containing a
   ``named.conf`` plus N RFC 1035 master files, OR a single
   ``named.conf`` for the rare case where every zone is inline (no
   reachable master file).
2. We unpack to a tempdir, locate ``named.conf``, and tokenise it for
   the ``zone "..." { ... };`` declarations — including any nested
   inside ``view "..." { ... };`` blocks.
3. For each zone declaration we resolve the ``file "..."`` directive
   to a real path inside the archive (honouring the optional
   ``options { directory "..." }`` directive), read it, and pass the
   text to the existing :func:`app.services.dns_io.parser.parse_zone_file`
   for the per-record canonical shape.
4. Result rolls up into an :class:`ImportPreview` the commit endpoint
   replays.

We deliberately do *not* try to parse the full named.conf grammar —
ACLs, controls, logging, key declarations all stay out of scope. The
importer touches zones + records only; the operator wires up TSIG /
ACL / forwarder configuration on the SpatiumDDI side post-import.
"""

from __future__ import annotations

import io
import re
import tarfile
import zipfile
from dataclasses import dataclass
from pathlib import Path
from tempfile import TemporaryDirectory
from typing import Iterable

from app.services.dns_io.parser import (
    ZoneParseError,
    parse_zone_file,
)

from .canonical import (
    ImportedRecord,
    ImportedSOA,
    ImportedZone,
    ImportPreview,
)


class ImportSourceError(ValueError):
    """Raised when the upload itself can't be processed.

    Per-zone parse errors don't raise this — they land in
    ``ImportPreview.warnings`` so the operator sees the partial
    success and can fix-and-reupload incrementally.
    """


# Hard cap on uploaded archives. BIND9 production configs in our
# field tests fit comfortably under 10 MB (a 10k-record zone is ~1
# MB plain text); 50 MB lets the rare giant zone through and stops a
# 4 GB tarball from blowing out memory on unpack.
MAX_ARCHIVE_BYTES = 50 * 1024 * 1024
MAX_UNPACKED_BYTES = 200 * 1024 * 1024  # tar bombs blowing past archive size

# Record types we drop on import with a warning. DNSSEC keys + their
# signatures get re-generated by SpatiumDDI's online-signing pipeline
# post-import (operator opts in via the zone-edit DNSSEC tab); the
# rest are historic / experimental rdtypes we don't model.
_DNSSEC_RECORDS = {"DNSKEY", "RRSIG", "NSEC", "NSEC3", "NSEC3PARAM", "DS", "CDS", "CDNSKEY"}


# ── named.conf tokenizer ─────────────────────────────────────────────


_COMMENT_BLOCK_RE = re.compile(r"/\*.*?\*/", re.DOTALL)
_COMMENT_LINE_RE = re.compile(r"(//|#)[^\n]*")
# Match a quoted name + opening brace. Used for both ``zone "name" {``
# and ``view "name" {``. Whitespace tolerant; the quote is required
# (BIND accepts unquoted names too but every export tool we've seen
# emits quoted; if we get an unquoted name the zone is silently
# skipped — operator quotes it manually and re-uploads).
_NAME_BLOCK_RE = re.compile(r'\s+"([^"]+)"\s*\{')


@dataclass
class _NamedConfZone:
    """One ``zone "name" { ... };`` declaration with its enclosing
    ``view`` (if any) and the raw body text — body still needs
    parsing for the ``type`` / ``file`` / ``masters`` directives."""

    name: str  # FQDN, may or may not have trailing dot
    body: str
    view: str | None


def _strip_comments(text: str) -> str:
    """Strip BIND's three comment styles in declaration order.

    ``/* … */`` first because line-style sequences (``//`` / ``#``)
    can legitimately live inside one. Done as two separate regex
    sweeps; named.conf is always small so the cost is irrelevant.
    """

    text = _COMMENT_BLOCK_RE.sub("", text)
    text = _COMMENT_LINE_RE.sub("", text)
    return text


def _balanced_block(text: str, brace_open_pos: int) -> tuple[str, int]:
    """Return ``(body, end_pos)`` where ``body`` is the content
    between ``{`` and the matching ``}`` (exclusive both sides) and
    ``end_pos`` is one past the closing ``}``.

    Naive depth counter is fine here — by the time we call this the
    text has already had comments stripped, so a stray ``}`` inside
    a quoted string is the only edge case. We handle quoted strings
    at byte level (good enough for named.conf — strings can't span
    lines).
    """

    depth = 1
    i = brace_open_pos + 1
    n = len(text)
    while i < n:
        ch = text[i]
        if ch == '"':
            # skip to closing quote
            j = text.find('"', i + 1)
            if j < 0:
                raise ImportSourceError("Unterminated string in named.conf")
            i = j + 1
            continue
        if ch == "{":
            depth += 1
        elif ch == "}":
            depth -= 1
            if depth == 0:
                return text[brace_open_pos + 1 : i], i + 1
        i += 1
    raise ImportSourceError("Unbalanced braces in named.conf")


def _walk_zones(text: str, view: str | None = None) -> Iterable[_NamedConfZone]:
    """Yield every ``zone`` declaration, recursing into ``view``
    blocks so we capture per-view zones with their view tag."""

    pos = 0
    n = len(text)
    while pos < n:
        m = re.search(r"\b(zone|view)\b", text[pos:])
        if not m:
            return
        kw = m.group(1)
        after_kw = pos + m.end()
        # Try to match the ``"name" {`` pattern; if it doesn't, this
        # was a stray identifier (e.g. ``allow-zone-transfer``) and
        # we step past it.
        nm = _NAME_BLOCK_RE.match(text, after_kw)
        if not nm:
            pos = after_kw
            continue
        name = nm.group(1)
        brace_open = nm.end() - 1
        try:
            body, end = _balanced_block(text, brace_open)
        except ImportSourceError:
            return
        if kw == "zone":
            yield _NamedConfZone(name=name, body=body, view=view)
        else:  # view
            yield from _walk_zones(body, view=name)
        pos = end


def _parse_options_directory(text: str) -> str | None:
    """Extract ``options { directory "/path"; }`` if present."""
    m = re.search(r"\boptions\b\s*\{", text)
    if not m:
        return None
    try:
        body, _ = _balanced_block(text, m.end() - 1)
    except ImportSourceError:
        return None
    dm = re.search(r'\bdirectory\s+"([^"]+)"\s*;', body)
    return dm.group(1) if dm else None


def _zone_directive(body: str, name: str) -> str | None:
    """Pull a single quoted directive value (``type "primary"`` →
    ``primary``, ``file "foo.zone"`` → ``foo.zone``) from a zone
    body. Returns None if absent or malformed.

    Quoting in BIND zone bodies is mostly optional. We accept both
    quoted (``type "primary";``) and bare (``type primary;``) forms.
    """

    qm = re.search(rf'\b{re.escape(name)}\s+"([^"]+)"\s*;', body)
    if qm:
        return qm.group(1)
    bm = re.search(rf"\b{re.escape(name)}\s+([^\s;]+)\s*;", body)
    return bm.group(1) if bm else None


def _zone_list_directive(body: str, name: str) -> list[str]:
    """Pull a list-shaped directive (``forwarders { 1.1.1.1; 8.8.8.8; };``)
    from a zone body. Returns ``[]`` if absent."""

    m = re.search(rf"\b{re.escape(name)}\s*\{{", body)
    if not m:
        return []
    try:
        inner, _ = _balanced_block(body, m.end() - 1)
    except ImportSourceError:
        return []
    return [
        token.strip().strip('"')
        for token in inner.split(";")
        if token.strip() and token.strip() != "/*" and not token.strip().startswith("//")
    ]


# ── Archive unpack ───────────────────────────────────────────────────


def _safe_extract_zip(archive: zipfile.ZipFile, dest: Path) -> int:
    """Extract ``archive`` to ``dest`` rejecting any path that escapes
    ``dest``. Returns total bytes written."""

    total = 0
    for member in archive.infolist():
        # ZIP filenames are forward-slash only per the spec; resolve
        # against dest and reject anything that escapes.
        target = (dest / member.filename).resolve()
        if not str(target).startswith(str(dest.resolve())):
            raise ImportSourceError(f"Archive member escapes root: {member.filename}")
        if member.is_dir():
            target.mkdir(parents=True, exist_ok=True)
            continue
        target.parent.mkdir(parents=True, exist_ok=True)
        with archive.open(member) as src, open(target, "wb") as dst:
            data = src.read()
            total += len(data)
            if total > MAX_UNPACKED_BYTES:
                raise ImportSourceError("Archive unpack exceeds size cap (200 MB)")
            dst.write(data)
    return total


def _safe_extract_tar(archive: tarfile.TarFile, dest: Path) -> int:
    """Same as :func:`_safe_extract_zip` for tar shapes. Strips
    leading slashes so absolute member paths land inside ``dest``."""

    total = 0
    for member in archive.getmembers():
        # Reject device files / symlinks / hardlinks — they have no
        # business in a config archive and they're the path-traversal
        # vectors. Regular files + dirs only.
        if not (member.isreg() or member.isdir()):
            raise ImportSourceError(f"Archive member type not allowed: {member.name}")
        member_name = member.name.lstrip("/")
        target = (dest / member_name).resolve()
        if not str(target).startswith(str(dest.resolve())):
            raise ImportSourceError(f"Archive member escapes root: {member.name}")
        if member.isdir():
            target.mkdir(parents=True, exist_ok=True)
            continue
        target.parent.mkdir(parents=True, exist_ok=True)
        f = archive.extractfile(member)
        if f is None:
            continue
        data = f.read()
        total += len(data)
        if total > MAX_UNPACKED_BYTES:
            raise ImportSourceError("Archive unpack exceeds size cap (200 MB)")
        with open(target, "wb") as dst:
            dst.write(data)
    return total


def _unpack(payload: bytes, dest: Path) -> None:
    """Detect ZIP vs tar (any compression) and dispatch to the safe
    extractor."""

    if len(payload) > MAX_ARCHIVE_BYTES:
        raise ImportSourceError(f"Archive too large (max {MAX_ARCHIVE_BYTES // 1024 // 1024} MB)")
    bio = io.BytesIO(payload)
    if zipfile.is_zipfile(bio):
        bio.seek(0)
        with zipfile.ZipFile(bio) as zf:
            _safe_extract_zip(zf, dest)
        return
    bio.seek(0)
    try:
        with tarfile.open(fileobj=bio, mode="r:*") as tf:
            _safe_extract_tar(tf, dest)
        return
    except tarfile.TarError as exc:
        raise ImportSourceError(f"Archive is neither ZIP nor tar: {exc}") from exc


# ── File location ────────────────────────────────────────────────────


def _find_named_conf(root: Path) -> Path | None:
    """Locate ``named.conf`` (any nested depth). Prefer the shallowest
    match so an export that ships ``etc/bind/named.conf`` plus a
    backup copy somewhere deeper picks the canonical one."""

    candidates = sorted(root.rglob("named.conf"), key=lambda p: len(p.parts))
    return candidates[0] if candidates else None


def _resolve_zone_file(root: Path, conf_dir: Path, options_dir: str | None, file_value: str) -> Path | None:
    """Resolve a ``file "..."`` directive to an actual path on disk.

    Strategy:

    1. If the path is absolute and exists relative to the archive
       root (operator preserved a /var/named layout), use that.
    2. If ``options { directory "..." }`` is set, resolve relative
       to it (and check both the literal and lstripped forms).
    3. Resolve relative to the directory holding ``named.conf``.
    4. Last-resort: case-insensitive basename search anywhere in
       the archive.

    Returns None if nothing matches. The caller surfaces the zone
    in ``warnings`` so the operator knows which file went missing.
    """

    target_basename = file_value.split("/")[-1]

    # Strategy 1: absolute → relative to archive root
    if file_value.startswith("/"):
        cand = root / file_value.lstrip("/")
        if cand.is_file():
            return cand

    # Strategy 2: options.directory
    if options_dir:
        opts_root = root / options_dir.lstrip("/")
        cand = opts_root / file_value.lstrip("/")
        if cand.is_file():
            return cand
        cand = opts_root / target_basename
        if cand.is_file():
            return cand

    # Strategy 3: relative to named.conf
    cand = conf_dir / file_value
    if cand.is_file():
        return cand

    # Strategy 4: basename search
    matches = [p for p in root.rglob(target_basename) if p.is_file()]
    return matches[0] if matches else None


# ── Public entry point ───────────────────────────────────────────────


def _classify_zone(name: str) -> str:
    """``forward`` or ``reverse``. Reverse zones live under
    ``in-addr.arpa.`` (IPv4) or ``ip6.arpa.`` (IPv6)."""
    n = name.lower().rstrip(".")
    if n.endswith(".in-addr.arpa") or n == "in-addr.arpa":
        return "reverse"
    if n.endswith(".ip6.arpa") or n == "ip6.arpa":
        return "reverse"
    return "forward"


def _normalize_zone_name(name: str) -> str:
    return name if name.endswith(".") else name + "."


def _parse_one_zone(decl: _NamedConfZone, root: Path, conf_dir: Path, options_dir: str | None) -> ImportedZone:
    """Turn one named.conf zone declaration into the canonical
    :class:`ImportedZone` shape. Per-zone parse errors land in
    ``parse_warnings`` so a bad zone doesn't kill the whole import.
    """

    body = _strip_comments(decl.body)
    zone_type_raw = (_zone_directive(body, "type") or "primary").lower()
    # Map BIND type values to our internal vocabulary. ``master`` is
    # the legacy synonym for ``primary``; ``slave`` for ``secondary``.
    zone_type = {
        "master": "primary",
        "primary": "primary",
        "slave": "secondary",
        "secondary": "secondary",
        "stub": "stub",
        "forward": "forward",
        "hint": "primary",  # rare — treat as primary so we at least carry the records
    }.get(zone_type_raw, "primary")

    fqdn = _normalize_zone_name(decl.name)
    kind = _classify_zone(fqdn)

    forwarders = _zone_list_directive(body, "forwarders") if zone_type == "forward" else []

    soa: ImportedSOA | None = None
    records: list[ImportedRecord] = []
    skipped: dict[str, int] = {}
    warnings: list[str] = []

    file_value = _zone_directive(body, "file")
    if zone_type in {"primary", "secondary"} and file_value:
        zone_path = _resolve_zone_file(root, conf_dir, options_dir, file_value)
        if zone_path is None:
            warnings.append(
                f"Zone file not found in archive: {file_value!r} — zone metadata imported, records skipped"
            )
        else:
            try:
                text = zone_path.read_text(encoding="utf-8", errors="replace")
            except OSError as exc:
                warnings.append(f"Could not read zone file {file_value!r}: {exc}")
            else:
                try:
                    parsed = parse_zone_file(text, fqdn)
                except ZoneParseError as exc:
                    warnings.append(f"Zone {fqdn!r} failed to parse: {exc}")
                else:
                    if parsed.soa is not None:
                        soa = ImportedSOA(
                            primary_ns=parsed.soa.primary_ns,
                            admin_email=parsed.soa.admin_email,
                            serial=parsed.soa.serial,
                            refresh=parsed.soa.refresh,
                            retry=parsed.soa.retry,
                            expire=parsed.soa.expire,
                            minimum=parsed.soa.minimum,
                            ttl=parsed.soa.ttl,
                        )
                    for r in parsed.records:
                        # Strip DNSSEC records — re-signed post-import
                        # via the online-signing pipeline.
                        if r.record_type in _DNSSEC_RECORDS:
                            skipped[r.record_type] = skipped.get(r.record_type, 0) + 1
                            continue
                        records.append(
                            ImportedRecord(
                                name=r.name,
                                record_type=r.record_type,
                                value=r.value,
                                ttl=r.ttl,
                                priority=r.priority,
                                weight=r.weight,
                                port=r.port,
                            )
                        )
                    if skipped:
                        total = sum(skipped.values())
                        warnings.append(
                            f"Zone {fqdn!r}: stripped {total} DNSSEC record(s) "
                            f"({', '.join(f'{k}={v}' for k, v in sorted(skipped.items()))}) — re-sign post-import via the zone DNSSEC tab"
                        )

    return ImportedZone(
        name=fqdn,
        zone_type=zone_type,
        kind=kind,
        soa=soa,
        records=records,
        view_name=decl.view,
        forwarders=forwarders,
        skipped_record_types=skipped,
        parse_warnings=warnings,
    )


def parse_bind9_archive(payload: bytes) -> ImportPreview:
    """Top-level entry point for the BIND9 importer.

    Takes the raw archive bytes from the multipart upload and returns
    the canonical :class:`ImportPreview` ready for the UI. The
    ``conflicts`` list is always empty here — the commit endpoint
    fills it in by querying the target group + view; this function
    is purely a parser and stays free of DB dependencies (which
    keeps unit testing cheap).
    """

    if not payload:
        raise ImportSourceError("Empty upload")

    # Run unpack + parse inside a temp dir so we never leave files
    # on disk after the request. ``TemporaryDirectory`` cleans up
    # even on exception via its context manager.
    with TemporaryDirectory(prefix="spddi-bind9-import-") as td:
        root = Path(td)
        _unpack(payload, root)

        named_conf = _find_named_conf(root)
        if named_conf is None:
            raise ImportSourceError(
                "No named.conf found in the archive. "
                "Include /etc/bind/named.conf (or /etc/named.conf) and any "
                "referenced zone files."
            )

        conf_text = _strip_comments(
            named_conf.read_text(encoding="utf-8", errors="replace")
        )
        options_dir = _parse_options_directory(conf_text)
        decls = list(_walk_zones(conf_text))

        if not decls:
            raise ImportSourceError(
                "named.conf contained no zone declarations. "
                "Phase 1 imports primary / secondary / stub / forward zones from "
                "named.conf — make sure your config has at least one ``zone {…}`` block."
            )

        zones: list[ImportedZone] = []
        warnings: list[str] = []
        seen_views: set[str] = set()
        for decl in decls:
            zones.append(_parse_one_zone(decl, root, named_conf.parent, options_dir))
            if decl.view is not None:
                seen_views.add(decl.view)

        # View handling: Phase 1 collapses everything to default view
        # and warns. The flag is per-import so split-horizon configs
        # produce one warning instead of one per zone.
        if len(seen_views) > 1 or (
            len(seen_views) == 1 and any(z.view_name is None for z in zones)
        ):
            warnings.append(
                f"Source carries {len(seen_views)} view(s): {sorted(seen_views)}. "
                "Phase 1 collapses everything to the default view; enable issue #24 (DNS Views) "
                "to separate them at apply time."
            )

        total_records = sum(len(z.records) for z in zones)
        histogram: dict[str, int] = {}
        for z in zones:
            for k, v in z.record_type_histogram.items():
                histogram[k] = histogram.get(k, 0) + v

    return ImportPreview(
        source="bind9",
        zones=zones,
        conflicts=[],  # filled by the commit endpoint via DB lookup
        warnings=warnings,
        total_records=total_records,
        record_type_histogram=histogram,
    )
