apiVersion: v2
name: spatium-dns
description: SpatiumDDI managed DNS servers (BIND9 / PowerDNS) with sidecar agent
type: application
version: 0.1.0
appVersion: "2026.04.14.1"
home: https://spatiumddi.org
sources:
  - https://github.com/spatiumddi
maintainers:
  - name: SpatiumDDI Contributors
