"""Host patch 002 — canonicalise the k3s CIDR drop-in in place (#974).

The installer fix only reaches FRESH installs. ``spatium-cidrs.yaml`` is
written under the /etc overlay, so it lives on the persistent ``/var``
and survives every slot swap — an appliance installed before the fix
carries its host-bits-set literal straight across the k3s v1.36 upgrade,
which is exactly the population the change is for. Patch 002 repairs it
through the #395 host-migration framework.

The properties worth pinning are the conservative ones, because this
patch edits a file that decides whether k3s starts:

* it changes ONLY the two network-valued keys, never ``cluster-dns``,
  the comment header, or anything else in the file;
* an unparseable value is left exactly as found — rewriting something we
  do not understand is how a repair becomes an outage;
* it is idempotent and writes nothing when the file is already canonical
  (a needless rewrite on every boot is churn on the persistent volume);
* a missing file is a no-op success, not a failure — a patch that
  returns non-zero blocks the trial-boot slot commit.

HOW TO RUN (from the repo root or this directory):
    python3 -m pytest appliance/tests/test_k3s_cidr_patch.py -v
"""

from __future__ import annotations

import shutil
import subprocess
from pathlib import Path

import pytest

PATCH = (
    Path(__file__).parent.parent
    / "mkosi.extra"
    / "usr"
    / "lib"
    / "spatiumddi"
    / "host-patches"
    / "002-k3s-cidr-canonical.sh"
)

HEADER = """# Auto-generated by spatium-install (issue #302) — operator-chosen
# k3s pod + service CIDRs from the install wizard.
#
# These CANNOT be changed in-place — k3s does not support live CIDR
# migration.
"""


def _run(dropin: Path) -> subprocess.CompletedProcess:
    return subprocess.run(
        ["sh", str(PATCH)],
        capture_output=True,
        text=True,
        env={"PATH": "/usr/bin:/bin:/usr/local/bin", "SPATIUM_K3S_CIDR_DROPIN": str(dropin)},
    )


def _write(tmp_path: Path, body: str) -> Path:
    p = tmp_path / "spatium-cidrs.yaml"
    p.write_text(HEADER + body, encoding="utf-8")
    return p


pytestmark = pytest.mark.skipif(shutil.which("sh") is None, reason="sh not on PATH")


def test_masks_host_bits(tmp_path: Path) -> None:
    p = _write(
        tmp_path,
        "cluster-cidr: 10.42.0.5/16\nservice-cidr: 10.43.9.9/16\ncluster-dns: 10.43.0.10\n",
    )
    r = _run(p)
    assert r.returncode == 0, r.stderr
    out = p.read_text(encoding="utf-8")
    assert "cluster-cidr: 10.42.0.0/16" in out
    assert "service-cidr: 10.43.0.0/16" in out


def test_cluster_dns_and_comments_survive(tmp_path: Path) -> None:
    """cluster-dns is an address, not a network — masking must not touch
    it, and the header explains the file to the next operator."""
    p = _write(
        tmp_path,
        "cluster-cidr: 10.42.0.5/16\nservice-cidr: 10.43.0.0/16\ncluster-dns: 10.43.0.10\n",
    )
    assert _run(p).returncode == 0
    out = p.read_text(encoding="utf-8")
    assert "cluster-dns: 10.43.0.10" in out
    assert out.startswith(HEADER)


def test_already_canonical_is_not_rewritten(tmp_path: Path) -> None:
    p = _write(
        tmp_path,
        "cluster-cidr: 10.42.0.0/16\nservice-cidr: 10.43.0.0/16\ncluster-dns: 10.43.0.10\n",
    )
    before = p.read_text(encoding="utf-8")
    mtime = p.stat().st_mtime_ns
    r = _run(p)
    assert r.returncode == 0
    assert p.read_text(encoding="utf-8") == before
    assert p.stat().st_mtime_ns == mtime, "rewrote a file that needed no change"


def test_idempotent(tmp_path: Path) -> None:
    p = _write(tmp_path, "cluster-cidr: 10.42.0.5/16\nservice-cidr: 10.43.0.0/16\n")
    assert _run(p).returncode == 0
    once = p.read_text(encoding="utf-8")
    assert _run(p).returncode == 0
    assert p.read_text(encoding="utf-8") == once


def test_unparseable_value_is_left_alone(tmp_path: Path) -> None:
    """Leading zeros are in this class — Python's ipaddress rejects them,
    and so does the installer's validator. Not ours to reinterpret."""
    p = _write(tmp_path, "cluster-cidr: 010.42.0.0/16\nservice-cidr: 10.43.0.5/16\n")
    r = _run(p)
    assert r.returncode == 0, r.stderr
    out = p.read_text(encoding="utf-8")
    assert "cluster-cidr: 010.42.0.0/16" in out
    # ...while the sibling key it CAN read is still repaired.
    assert "service-cidr: 10.43.0.0/16" in out


def test_missing_file_is_a_no_op_success(tmp_path: Path) -> None:
    """A non-zero exit blocks the trial-boot slot commit. A node with no
    drop-in has nothing to repair; that is not a failed upgrade."""
    r = _run(tmp_path / "absent.yaml")
    assert r.returncode == 0


def test_ipv6_is_masked_too(tmp_path: Path) -> None:
    p = _write(tmp_path, "cluster-cidr: fd00:42::5/56\nservice-cidr: fd00:43::/112\n")
    assert _run(p).returncode == 0
    assert "cluster-cidr: fd00:42::/56" in p.read_text(encoding="utf-8")


def test_dual_stack_lists_are_left_alone(tmp_path: Path) -> None:
    """k3s accepts a comma-joined pair for dual-stack. The regex matches
    one network per value, so a list does not parse and is passed
    through rather than mangled — the wizard is IPv4-only today, and
    silently rewriting half of a dual-stack value would be worse than
    leaving it."""
    p = _write(tmp_path, "cluster-cidr: 10.42.0.5/16,fd00:42::5/56\n")
    assert _run(p).returncode == 0
    assert "cluster-cidr: 10.42.0.5/16,fd00:42::5/56" in p.read_text(encoding="utf-8")


def test_patch_is_executable() -> None:
    """spatium-host-migrate runs the patch by path; the +x bit must be
    committed (and mirrored in mkosi.postinst's chmod block)."""
    assert PATCH.stat().st_mode & 0o111, f"{PATCH} is not executable"
