{{- if and (not .Values.agentKey.existingSecret) .Values.agentKey.value }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.agentKey.secretName }}
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  DNS_AGENT_KEY: {{ .Values.agentKey.value | quote }}
{{- end }}
