{{- $root := . -}}
{{- range $server := .Values.servers }}
---
apiVersion: v1
kind: Service
metadata:
  name: dns-{{ $server.flavor }}-{{ $server.name }}
  namespace: {{ $root.Release.Namespace }}
spec:
  type: {{ default "LoadBalancer" (get (default dict $server.service) "type") }}
  selector:
    app.kubernetes.io/name: spatium-dns
    app.kubernetes.io/instance: {{ $server.name }}
  ports:
    - { name: dns-udp, port: 53, targetPort: 53, protocol: UDP }
    - { name: dns-tcp, port: 53, targetPort: 53, protocol: TCP }
---
apiVersion: v1
kind: Service
metadata:
  name: dns-{{ $server.flavor }}-{{ $server.name }}-headless
  namespace: {{ $root.Release.Namespace }}
spec:
  clusterIP: None
  selector:
    app.kubernetes.io/name: spatium-dns
    app.kubernetes.io/instance: {{ $server.name }}
  ports:
    - { name: dns-udp, port: 53, protocol: UDP }
    - { name: dns-tcp, port: 53, protocol: TCP }
{{- end }}
